---
title: "Data Science - Final Project Proposal"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




##### Group Members (names and UNIs): 
Ifrah Fayyaz (if2282), Lydia Parr (lcp2148), Lauren Cohen (lcc2181), Onyeka Isamah (oi2142), Riddhi Thakkar (rt2640) 


**The tentative project title:**
Predictors of depression risk in older adults


**The motivation for this project:**
To identify predictors of negative mental health outcomes among older adults given that they are known to have higher risk of depression than the general population. 

**The intended final products:**

- Written report
- Webpage that includes an "about" section, a dashboard page that includes visualizations and exploratory statistical analyses
- A 2-minute narrated screencast that illustrates our project

**The anticipated data sources:**
National Health and Aging Trends Study from Johns Hopkins and Westat 

**The planned analyses / visualizations / coding challenges:**

*Outcomes*: Emotional well-being, or depression risk using the PHQ-2 depression scale (derived with two variables, hc[round#]depresan1 and hc[round#]depresan2 that are summed)

*Tentative predictors and covariates*: Gender, age, race, whether participant uses mobility devices, size of social network, whether or not they have no one to talk to, self reported memory issues causing problems, if dementia is reason for a proxy (note this variable is only relevant for people who have a proxy, so we can't omit missing/NA for this variable), self-rated health, and whether they are happy with their living situation. 

*Relevant information from literature for our intro*: Previous literature has examined a wide range of risk factors for depression in older adults. Older age, female gender, isolation, and physical health have all be found to be risk factors for depression in older adults (Sözeri-Varma). Memory issues and disorders affecting cognition are also associated with depression risk (Köhler et al, 2010). Depression risk in older adults is also associated with race and ethnicity, with evidence certain groups have a higher risk of depression (Hooker et al, 2019). The outcome will be the PHQ-2, which sums two variables rating mood and well-being on a Likert scale (validated by Kroenke et al, 2003, but this outcome is also used by Hooker et al with 3 as cutoff value, so we could just cite that and be fine)

Hooker, K., Phibbs, S., Irvin, V. L., Mendez-Luck, C. A., Doan, L. N., Li, T., Turner, S., & Choun, S. (2019). Depression Among Older Adults in the United States by Disaggregated Race and Ethnicity. *The Gerontologist, 59*(5), 886–891. https://doi.org/10.1093/geront/gny159

Köhler, S., Thomas, A. J., Barnett, N. A., & O'Brien, J. T. (2010). The pattern and course of cognitive impairment in late-life depression. *Psychological medicine, 40*(4), 591–602. https://doi.org/10.1017/S0033291709990833

Kroenke K., Spitzer R.L., Williams J.B. (2003). The Patient Health Questionnaire-2: Validity of a Two-Item Depression Screener. *Medical Care 41,* 1284-92.

Sözeri-Varma G. (2012). Depression in the elderly: clinical features and risk factors. *Aging and disease, 3*(6), 465–471.

We would also like to visualize how the association between predictor(s) and outcomes change over time, possibly using a growth curve model. 

**The planned timeline:** 

- November 13 by 1:00 pm	| Form a team and submit a proposal	Written proposal document
- November 16-19	        | Project review meeting	Zoom meeting – no “deliverable”
- November 20 by 9:00 pm  | Data cleaning / initial analysis / initial visuals
- November 27 by 9:00pm   | First check-in meeting
- December 05 by 9:00 pm  | Second check-in meeting
- December 11 by 4:00 pm	| Report	Written report giving detailed project description
- December 11 by 4:00 pm	| Webpage and screencast	Webpage overview of project, with short explanatory video (published online)
- December 11 by 8:00 pm	| Peer assessment	Brief assessment of your teammates contributions (as a short document)
- December 16	            | “In class” discussion of projects	Enjoy hearing about projects! (Also get hex stickers)

